return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "c",
      "cpp",
      "lua",
      "vim",
      "vimdoc",
      "query",
      "javascript",
      "typescript",
      "html",
      "css",
      "json",
      "yaml",
      "toml",
      "bash",
      "python",
      "cmake",
      "dockerfile",
      "markdown",
      "markdown_inline",
      "xml",
      "rust",
    },
    highlight = { enable = true },
    indent = { enable = true },
  },
}
